# Generated by Django 5.2 on 2025-04-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_de_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
