# Generated by Django 5.2 on 2025-05-11 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_cliente_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto_carnet',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_carnet/'),
        ),
    ]
